// docs/src/.vitepress/theme/Frame.vue
<template>
  <iframe
    :src="`https://web.project-graph.top/?frame=true&file=${dataBase64}`"
    frameborder="0"
    width="100%"
    height="400px"
    ref="el"
    @mouseenter="el.focus()"
  ></iframe>
</template>

<script setup lang="ts">
import { computed, ref } from "vue";

const { data } = defineProps<{
  data: Record<string, any>;
}>();

const el = ref<HTMLIFrameElement>(null);

const dataBase64 = computed(() => {
  const binString = Array.from(new TextEncoder().encode(JSON.stringify(data)), (byte) =>
    String.fromCodePoint(byte),
  ).join("");
  return btoa(binString);
});
</script>

// docs/app/components/Frame.tsx
import React from "react";

interface Props {
  data: Record<string, any>;
}

const Frame: React.FC<Props> = ({ data }) => {
  // const [el, setEl] = useState<HTMLIFrameElement | null>(null);

  return (
    <iframe
      src={`https://web.project-graph.top/?frame=true&file=${btoa(
        Array.from(new TextEncoder().encode(JSON.stringify(data)), (byte) => String.fromCharCode(byte)).join(""),
      )}`}
      width="100%"
      height="400px"
      // ref={setEl}
      // onMouseEnter={() => el?.focus()}
    />
  );
};

export default Frame;
